name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: registry
      - uses: actions/deploy-pages@v4
